name: Expressions Workflow

on:
  workflow_dispatch:
    inputs:
      number:
        description: "Enter a number to evaluate"
        required: true
        type: string

jobs:
  expression-demo:
    runs-on: ubuntu-latest
    steps:
      # Normal Function Examples
      - name: String Functions
        run: |
          echo "Uppercase: ${{ toUpper('hello') }}"
          echo "Lowercase: ${{ toLower('WORLD') }}"
          echo "Replace: ${{ replace('Hello World', 'World', 'GitHub') }}"

      # Format Function
      - name: Format Function
        run: |
          echo "${{ format('Hello {0} {1}!', 'GitHub', 'Actions') }}"

      # Math Functions
      - name: Math Operations
        run: |
          echo "Input number plus 10: ${{ fromJSON(inputs.number) + 10 }}"
          echo "Maximum value: ${{ max(3, 5, 2, 4) }}"
          echo "Minimum value: ${{ min(3, 5, 2, 4) }}"

      # Status Check Functions
      - name: Status Check Functions
        run: |
          echo "Success: ${{ success() }}"
          echo "Always: ${{ always() }}"
          echo "Failure: ${{ failure() }}"

      # Conditional Step
      - name: Conditional Step
        if: ${{ contains('Hello World', 'World') }}
        run: echo "Condition was true!"
