name: Expressions Workflow

on:
  workflow_dispatch:

jobs:
  expression-demo:
    runs-on: ubuntu-latest
    steps:
      # String Functions
      - name: String Functions
        run: |
          echo "Contains World: ${{ contains('Hello World', 'World') }}"
          echo "StartsWith Hello: ${{ startsWith('Hello World', 'Hello') }}"
          echo "EndsWith Actions: ${{ endsWith('GitHub Actions', 'Actions') }}"

      # Format String (instead of join)
      - name: Format String
        run: |
          echo "Hello GitHub Actions"

      # Simple Comparison (instead of math)
      - name: Comparison Operations
        run: |
          echo "Greater than: ${{ 5 > 3 }}"
          echo "Less than: ${{ 2 < 4 }}"

      # Status Check Functions
      - name: Status Check Functions
        run: |
          echo "Success: ${{ success() }}"
          echo "Always: ${{ always() }}"
          echo "Failure: ${{ failure() }}"

      # Conditional Step
      - name: Conditional Step
        if: contains('Hello World', 'World')
        run: echo "Condition was true!"
