name: Expressions Workflow

on:
  workflow_dispatch:

jobs:
  expression-demo:
    runs-on: ubuntu-latest
    steps:
      # String Functions
      - name: String Functions
        run: |
          echo "Contains World: ${{ contains('Hello World', 'World') }}"
          echo "StartsWith Hello: ${{ startsWith('Hello World', 'Hello') }}"
          echo "EndsWith Actions: ${{ endsWith('GitHub Actions', 'Actions') }}"

      # Format String
      - name: Format String
        run: |
          echo "Hello GitHub Actions"

      # Simple Comparison
      - name: Comparison Operations
        run: |
          echo "Greater than: ${{ 5 > 3 }}"
          echo "Less than: ${{ 2 < 4 }}"

      # GitHub Context Values
      - name: GitHub Context Values
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Actor: ${{ github.actor }}"

      # Status Check using Environment Variables
      - name: Status Check with Environment Variables
        run: |
          echo "GitHub Ref: $GITHUB_REF"
          echo "GitHub Actor: $GITHUB_ACTOR"
          echo "GitHub Repository: $GITHUB_REPOSITORY"

      # Conditional Step
      - name: Conditional Step
        if: contains('Hello World', 'World')
        run: echo "Condition was true!"

      # Job Status Check - Alternative
      - name: Conditional Step Based on Job Status
        if: ${{ !failure() }}
        run: echo "This step runs if the job has not failed"
