name: Expressions Workflow

on:
  workflow_dispatch:

jobs:
  expression-demo:
    runs-on: ubuntu-latest
    steps:
      # String Functions
      - name: String Functions
        run: |
          echo "Contains World: ${{ contains('Hello World', 'World') }}"
          echo "StartsWith Hello: ${{ startsWith('Hello World', 'Hello') }}"
          echo "EndsWith Actions: ${{ endsWith('GitHub Actions', 'Actions') }}"

      # Join Function
      - name: Join Function
        run: |
          echo "${{ join(['Hello', 'GitHub', 'Actions'], ' ') }}"

      # Math Functions
      - name: Math Operations
        run: |
          echo "Maximum value: ${{ max(3, 5, 2, 4) }}"
          echo "Minimum value: ${{ min(3, 5, 2, 4) }}"

      # Status Check Functions
      - name: Status Check Functions
        run: |
          echo "Success: ${{ success() }}"
          echo "Always: ${{ always() }}"
          echo "Failure: ${{ failure() }}"

      # Conditional Step
      - name: Conditional Step
        if: contains('Hello World', 'World')
        run: echo "Condition was true!"
