name: Secrets and env pipeline

on:
  workflow_dispatch:
  inputs:
    secret:
      description: "Branch to run the workflow"
      required: true

env:
  my_dev_key: ${{ secrets.MY_DEV_KEY }}
  NODE_ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Print env variables
        run: |
          echo "MY_DEV_KEY: $my_dev_key"
          echo "NODE_ENV: $NODE_ENV"

      - name: Run shell cmd
        run: |
          echo "secret run successfully"
