name: "Webhook Workflow"

on:
  repository_dispatch:
    types:
      - webhook

jobs:
  respond-to-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Run a script
        run: |
          echo "This is an event of type: ${{ github.event_name }}"
