name: Workflow Commands

on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: "group logging"
        run: |
          echo "::group::This is the start of the group"
          echo "Message 1 ...."
          echo "Message 2 ...."
          echo "Message 3 ...."
          echo "::endgroup::"
